data_path: 
- https://storage.googleapis.com/python_mdg/carto_cursos/ar_properties.csv.gz
neighbors: 
- https://cdn.buenosaires.gob.ar/datosabiertos/datasets/ministerio-de-educacion/barrios/barrios.geojson